# Generated by Django 6.1 on 2026-09-09 07:16

from django.db import migrations, models


# The old choices had 'volunteer' and 'research', which LinkedIn has no equivalent
# for. Remap by title rather than by old value: the TA role was stored as
# 'part-time', which is still a valid choice, so only this row should move.
RECATEGORIZE = {
    'Teaching Assistant · Programming Foundation 1 (DDP1)': 'contract',
    'CTF Staff · COMPFEST 18': 'seasonal',
    'Member · NetSOS SIG': 'seasonal',
}


def recategorize(apps, schema_editor):
    Experience = apps.get_model('main', 'Experience')
    for title, category in RECATEGORIZE.items():
        Experience.objects.filter(title=title).update(category=category)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_seed_portfolio_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('self-employed', 'Self-employed'), ('freelance', 'Freelance'), ('contract', 'Contract'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship'), ('seasonal', 'Seasonal')], default='full-time', max_length=20),
        ),
        migrations.RunPython(recategorize, migrations.RunPython.noop),
    ]
