# Generated by Django 5.2.17 on 2026-09-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_experience_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='img/cert/'),
        ),
    ]
