# Generated by Django 5.2.17 on 2026-09-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_achievement_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='certificate',
            field=models.URLField(blank=True, null=True),
        ),
    ]
